spring.application.name=deckservice
springdoc.default-produces-media-type=application/json

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/deckservice}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-postgres.sql
